### ISSUE TITLE
Forced to update() every time

### ISSUE THREAD

**Issue by crbinz** [JuliaAstro/EarthOrientation.jl#2]
Every time I restart julia and use `EarthOrientation.jl`, I'm prompted to call `EarthOrientation.update()`. I've verified that the right files are in `EarthOrientation/data/` -- I think there's just no attempt made to load those files when the module is first loaded.

```julia
julia> using EarthOrientation

julia> getΔUT1(now())
ERROR: EOP_DATA is not available. Call 'EarthOrientation.update()' to load it.
```

**Comment by helgee** [comment]
Please excuse my late reply, I just came back from vacation.

There was initially an `__init__` function that just called `EarthOrientation.update()` but I removed it since that defeated the purpose of the user being able to manage the files himself.

I would like the explicity of a `EarthOrientation.load()` function but it is also tedious and I think your approach in #3, i.e. `__init__` being a no-op when the files are not there, might work well.
